name: ride_share
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # logic
  shared_preferences: ^2.3.3
  flutter_bloc: ^8.1.6
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.2.3
  get_it: ^8.0.2

  # data
  dio: ^5.7.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  equatable: ^2.0.0
  http: ^1.2.2

  # presentation
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  flutter_svg: ^2.0.16
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  material_floating_search_bar_2: ^0.5.0
  image_picker: ^1.1.2
  path: ^1.9.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.2
  flutter_rating_bar: ^4.0.1
  flutter_polygon: ^0.3.0+2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/normal/
    - assets/images/svg/
    - assets/files/

  fonts:
    - family: Almarai-Bold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf

    - family: Almarai-ExtraBold
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf

    - family: Almarai-Light
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf

    - family: Almarai-Regular
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
